### ISSUE TITLE
이 글꼴에 대응하는 날개셋 자판 배열을 만들어봤습니다.

### ISSUE THREAD

**Issue by ghost** [Tzetachi/Oesol-Serif-deprecated#1]
https://github.com/ZyntharSekki/Oesol-key
여기에 올려도 되는 건지는 모르겠지만...
사용자 지정 영역을 사용하다 보니 타이핑하는 데 지장이 있을 것 같아 한번 만들어봤습니다.
이 글꼴을 사용하는 데 도움이 되셨으면 합니다.

**Comment by Tzetachi** [comment]
안 그래도 날개셋으로 만들 생각만 하고 실행을 못 하던 차에 이렇게 직접 만들어 주시니 감사할 따름입니다. Oesol을 사용하는 데에 많은 도움이 될 것 같습니다.
